### ISSUE TITLE
Receptacle constructor

### ISSUE THREAD

**Issue by janus** [DylanPiercey/receptacle#1]
This is a bit hard for me to understand:

``` javascript
this.lastModified = new Date(options.lastModified || new Date);
```

I'm thinking that one could use this in its place:

``` javascript
this.lastModified = options.lastModified? new Date(options.lastModified): new Date();
```

Or is there something I am missing?

**Comment by DylanPiercey** [comment]
Both of those snippets execute the same. The `||` and `&&` operators return a value in javascript. The return value with both operators is always the last value that you can imagine was checked.

For example:

``` js
true || false //-> true
1 || 0 //-> 1

false || true //-> true
0 || 1 //-> 1
```

Because `||` always returns the truthy value its often used for default values. It reads (like you said) `if a then a else b`.

`&&` is used less for this kind of trickery but it basically says `if a and b then b else a`. Sometimes you will see it in JSX where you only want b to render if a.

Typed this up on my phone so let me know if I am not clear enough and I'll try to explain further.

A good reference for this is MDN https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators

**Comment by janus** [comment]
Thanks so much! 
But creating two objects at same time looks like it is not efficient in memory usage.

``` JavaScript
var foo = new Date(new Date);
```

**Comment by DylanPiercey** [comment]
@janus your right, it's not as optimized as it could be. I may change this is in update but the reality is that this code only runs at creation time for the cache so it isn't something that really needs to be worried about unless you plan on making huge amounts of caches. On top of that the Date constructor is pretty fast, especially at copying dates like we are doing here http://jsperf.com/date-copy-constructor/3.

**Comment by janus** [comment]
Thanks!

**Comment by janus** [comment]
I am just learning JS, and I am likely to study more of your code. However, if you know any libraries I  should study or code (in Vanilla JS) please send the such link.

**Comment by DylanPiercey** [comment]
I'd recommend reading the following if you can:
- JavaScript The Good Parts - Douglas Crockford
- JavaScript Patterns - Stoyan Stefanov
- Functional JavaScript - Michael Fogus

As for libraries to check out it's hard to say without knowing your experience level. Are you also using Node JS?

**Comment by janus** [comment]
Are you also using Node JS? Yes, I use it to run codes and to do quick prototype. 
My JS code base: https://github.com/janus/calendar , and https://github.com/janus/Calc.

I have read item 1, however I'll read it again.

**Comment by DylanPiercey** [comment]
If you haven't already I would check out https://github.com/sindresorhus/awesome.

It is a great resource for web development and lots of categories for you to dig into.
