### ISSUE TITLE
Cannot read property 'key' of undefined

### ISSUE THREAD

**Issue by oliviertassinari** [DylanPiercey/receptacle#3]
I have noticed the following issue on a production app (4k throws on 2k users so far):

> Cannot read property 'key' of undefined

It's coming from [that line](https://github.com/DylanPiercey/receptacle/blob/master/index.js#L97).
Any idea what could cause that?

**Comment by DylanPiercey** [comment]
What is max set to for the receptacle? Also would it be possible to get more of the stack trace?

**Comment by oliviertassinari** [comment]
We use a max value of `100`. I'm adding a try catch to investigate what's going one. No, I don't have much information.

**Comment by DylanPiercey** [comment]
@oliviertassinari do you by chance have a key called 'length'?

**Comment by oliviertassinari** [comment]
The key is supposed to be coming from the `key` property of *react-router*`.location.key`.
For instance `e43re1`.
We are investigating on the issue. I'm gonna let you now next week if we figure out what's going on

**Comment by DylanPiercey** [comment]
@oliviertassinari sweet sounds good. I am currently releasing a patch for two issues I noticed while scanning through the code today. Namely if you set 'length' or an integer as a key there would be issues since the lookup table and the array of items was the same object. Now these are separate and that issue should be gone.

Let me know if this solves your issue, if not I'm more than happy to continue digging.

**Comment by oliviertassinari** [comment]
Closing, still don't have any clue regarding what's going on.
